language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

install:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success:
  - travis_retry php coveralls.phar

notifications:
  email: false
